repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: fix-byte-order-marker
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        # No args to use pyproject.toml settings (line-length = 100)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=100,
            --extend-ignore=E203,
            --exclude=.venv,
            .pytest_cache,
          ]
        # Ensure flake8 receives files correctly
        pass_filenames: true
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest tests/
        language: system
        files: ^(src/|tests/).*\.py$
        pass_filenames: false
      - id: sphinx-build
        name: Build Sphinx documentation
        entry: powershell -Command "cd docs; make html"
        language: system
        files: ^(src/|docs/).*$
        pass_filenames: false
