repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: fix-byte-order-marker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--strict, --show-error-codes, --disable-error-code=import]
        exclude: ^docs/source/conf\.py$
        additional_dependencies: [numpy, pandas, pytest]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=100,
            --extend-ignore=E203,
            --exclude=.venv,
            .pytest_cache,
            bootstrap.py,
            docs/source/conf.py,
          ]
        pass_filenames: true
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        args: [--max-line-length=100, "--disable=C0114,F0401,E0611,C0327"]
        exclude: ^(docs/source/conf\.py|tests/__init__\.py|src/__init__\.py|src/config/|.*_generated\.py$|bootstrap\.py$)
        files: ^(src/|tests/).*\.py$
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest tests/
        language: system
        files: ^(src/|tests/).*\.py$
        pass_filenames: false
      - id: sphinx-build
        name: Build Sphinx documentation
        entry: powershell -Command "cd docs; make html"
        language: system
        files: ^(src/|docs/).*$
        pass_filenames: false
