name: Bug Report
description: Report a bug in the project
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug in detail.
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue.
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Environment
      description: Python version, OS, etc.
